language: java

jobs:
  include: 
    - stage: deploy
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t duck-ledger .
      - docker tag duck-ledger $DOCKER_USERNAME/duck-ledger
      - docker push $DOCKER_USERNAME/duck-ledger
